### PR TITLE
Versionning

### LINKED ISSUE #12: Versionning
- Make a release/tag of the project
- Have the version number in the binary
- Add a `version` command
- Send back the version in the root ressource cf #11 
- Add the commit hash in addition to the version

### PR DESCRIPTION
**Pull request by nlepage**
fix #12 
A test release 0.0.1 was performed based on this branch

### CODE REVIEW

**Comment by Nebulis** [comment]
If you dont run goru via docker image, you dont have the version 😕

**Comment by nlepage** [comment]
You mean when you build the binary yourself ?
One solution would be to attach the binary (with the version valued) to the github release.
Maybe I can do it automatically from Circle CI.

**Comment by Nebulis** [comment]
How can you attach the binary to the github release ?

My usecase is : i clone the project, then build and run and i dont have any version

**Comment by nlepage** [comment]
It is possible to add release assets via the github releases API : https://developer.github.com/v3/repos/releases/#upload-a-release-asset

For an average user, if the goal is to have a binary with a version number, I think it would be simpler to directly have binaries attached to the release.

What do you think ?

Anyways, I'm going to look if it's possible to have a default value for -X properties that would be satistfying.

**Comment by Nebulis** [comment]
I think it's well enough for the moment. Just have this use case somewhere in our minds ans maybe find something to resolve it

**Review by Nebulis — APPROVED** [review]

**Pull request merged**
